version: '3'

services:

  db:
      image: mariadb
      container_name: wbotcontainer
      restart: always
      ports: ['3306:3306']
      volumes:
       - mariadb-data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: wbot
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password

  phphmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmincontainer
    restart: always
    depends_on: ['db']
    ports: ['80:80']
    links: ['db:db']
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password

  wbot-application:
    image: wbot
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_USERNAME: 'user'
      SPRING_DATASOURCE_PASSWORD: 'password'
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/wbot
    build:
      context: './'
      dockerfile: 'Dockerfile'
    depends_on:
      - db

volumes:
  mariadb-data:
